import { QuizCollection } from "@/models/quizCollection";
import { Quiz } from "@/models/quiz";

export const idiomData = new QuizCollection([
  new Quiz("add to", "増大させる"),
  new Quiz("be responsible for", "～に責任がある"),
  new Quiz("be concerned about", "関心がある"),
  new Quiz("instead of", "代わりに"),
  new Quiz("account for", "（割合を）占める"),
  new Quiz("depend on", "～次第だ，～に依る"),
  new Quiz("be supposed to V", "Vすることとされている"),
  new Quiz("get rid of", "取り除く"),
  new Quiz("aim at", "目指す"),
  new Quiz("go through", "経験する"),
  new Quiz("date back", "さかのぼる"),
  new Quiz("lead to", "～につながる"),
  new Quiz("evolve into", "～に進化する"),
  new Quiz("such as", "～のような"),
  new Quiz("to name a few", "いくつか例を挙げるなら"),
  new Quiz("according to", "～によると"),
  new Quiz("regard A to B", "AをBと見做す"),
  new Quiz("keep up with", "（遅れないで）ついていく"),
  new Quiz("catch up with", "追いつく"),
  new Quiz("when it comes to", "～ということになると"),
  new Quiz("put on", "着る"),
  new Quiz("die out", "絶滅する"),
  new Quiz("due to", "～のために"),
  new Quiz("turn out", "～だと分かる"),
  new Quiz("tend to", "～する傾向にある"),
  new Quiz("be satisfied with", "～に満足する"),
  new Quiz("by itself", "ひとりでに"),
  new Quiz("get over", "乗り越える"),
  new Quiz("remind A of B", "AにBを思い出させる"),
  new Quiz("how to V", "どうVすべきか"),
  new Quiz("give my all", "私の全力を尽くす"),
  new Quiz("human beings", "人類，人間"),
]);
