import { Quiz } from "@/models/quiz";
import { QuizCollection } from "@/models/quizCollection";

export const wordData = new QuizCollection([
  new Quiz("major", "主な"),
  new Quiz("wrongly", "誤って、間違って"),
  new Quiz("imply", "暗示する"),
  new Quiz("ancestor", "祖先"),
  new Quiz("species", "種"),
  new Quiz("save", "貯める、節約する"),
  new Quiz("maintain", "維持する"),
  new Quiz("temperature", "温度"),
  new Quiz("opportunity", "機会"),
  new Quiz("option", "選択肢"),
  new Quiz("solution", "解決策"),
  new Quiz("nude", "裸の"),
  new Quiz("exceptional", "卓越した、例外的な"),
  new Quiz("alternative", "代わりの、代案"),
  new Quiz("offer", "提供する"),
  new Quiz("benefit", "利点"),
  new Quiz("steal", "盗む"),
  new Quiz("heartbroken", "悲しみに打ちひしがれた"),
  new Quiz("spread", "広がり"),
  new Quiz("facility", "施設"),
  new Quiz("resident", "入居者"),
  new Quiz("cause", "引き起こす"),
  new Quiz("boredom", "退屈"),
  new Quiz("anxiety", "心配"),
  new Quiz("option", "選択肢"),
  new Quiz("stimulate", "刺激する"),
  new Quiz("wage", "賃金"),
  new Quiz("earn", "稼ぐ"),
  new Quiz("require", "必要とする"),
  new Quiz("comfortably", "快適に"),
  new Quiz("productive", "生産的な"),
  new Quiz("remain", "〜のままである"),
  new Quiz("transportation", "交通機関"),
  new Quiz("cost", "費用"),
  new Quiz("vary", "変化する"),
  new Quiz("particular", "特定の"),
  new Quiz("guarantee", "保証する"),
  new Quiz("right", "権利"),
  new Quiz("fairly", "公正に"),
  new Quiz("labor", "労働"),
  new Quiz("claim", "主張する"),
  new Quiz("benefit", "利点"),
  new Quiz("reduce", "減らす"),
  new Quiz("financial", "財政の、金融の"),
  new Quiz("burden", "負担"),
  new Quiz("profit", "利益"),
  new Quiz("effect", "効果、影響"),
  new Quiz("completely", "完全に"),
  new Quiz("competitive", "競争力のある"),
  new Quiz("suffer", "被害にある、苦しむ"),
  new Quiz("put into action", "〜を実行する"),
  new Quiz("determine", "決定する"),
  new Quiz("improve", "改善する、向上する"),
  new Quiz("encourage", "奨励する、勧める"),
  new Quiz("current", "現在の"),
  new Quiz("law", "法律"),
  new Quiz("fail", "失敗する、〜し損なう"),
  new Quiz("evaluate", "評価する"),
]);
